### ISSUE TITLE
Offline compression with template inheritance

### ISSUE THREAD

**Issue by thenewguy** [django-compressor/django-compressor#1029]
I am getting OfflineGenerationError while running the compress command.
```
python manage.py compress --verbosity 3 --traceback
```

My templates are like this:

3rd party Template Base (the original base.html)

```
{% block scripts %}
    <script src="{% static 'awesome-script.js' %}"></script>
{% endblock %}
```

Template A (overrides and extends Template Base in the local project)
```
{% extends 'base.html' %}
{% load compress %}

{% block scripts %}
    {% compress js %}
        {{ block.super }}
    {% endcompress %}
{% endblock %}

```

Template B
```
{% extends 'Template A' %}

does nothing with respect to compressor
```

Template C
```
{% extends 'Template B' %}

(% block scripts %}
    {{ block.super }}
    {% compress js %}
        <script src="{% static 'some/script.js' %}"></script>
    {% endcompress %}
{% endblock %}
```

I get an error like:

```
 Traceback (most recent call last):
   File "manage.py", line 21, in <module>
     main()
   File "manage.py", line 17, in main
     execute_from_command_line(sys.argv)
   File "/long/path/to/django/core/management/__init__.py", line 401, in execute_from_command_line
     utility.execute()
   File "/long/path/to/django/core/management/__init__.py", line 395, in execute
     self.fetch_command(subcommand).run_from_argv(self.argv)
   File "/long/path/to/django/core/management/base.py", line 328, in run_from_argv
     self.execute(*args, **cmd_options)
   File "/long/path/to/django/core/management/base.py", line 369, in execute
     output = self.handle(*args, **options)
   File "/long/path/to/compressor/management/commands/compress.py", line 277, in handle
     self.handle_inner(**options)
   File "/long/path/to/compressor/management/commands/compress.py", line 300, in handle_inner
     offline_manifest, block_count, results = self.compress(engine, extensions, verbosity, follow_links, log)
   File "/long/path/to/compressor/management/commands/compress.py", line 225, in compress
     rendered = parser.render_nodelist(template, context, node)
   File "/long/path/to/compressor/offline/django.py", line 114, in render_nodelist
     return node.nodelist.render(context)
   File "/long/path/to/django/template/base.py", line 936, in render
     bit = node.render_annotated(context)
   File "/long/path/to/django/template/base.py", line 903, in render_annotated
     return self.render(context)
   File "/long/path/to/compressor/templatetags/compress.py", line 143, in render
     return self.render_compressed(context, self.kind, self.mode, forced=forced)
   File "/long/path/to/compressor/templatetags/compress.py", line 97, in render_compressed
     return self.render_offline(context)
   File "/long/path/to/compressor/templatetags/compress.py", line 82, in render_offline
     'is the original content:\n\n%s' % (key, original_content))
 compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "too-long-for-comfort" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:
```

Should this work?  Are templates sorted somehow so they are compressed in dependency order?

**Comment by karyon** [comment]
It looks like we have a test for that specific scenario: https://github.com/django-compressor/django-compressor/blob/24f6648/compressor/tests/test_offline.py#L348. It would be nice if you could check what the difference to your setup is.

**Comment by thenewguy** [comment]
So I had another set of templates raising an error similar to this.

```
django.core.management.base.CommandError: An error occurred during rendering /home/vagrant/.tox/compress_premigrate/lib/python3.6/site-packages/coderedcms/templates/coderedcms/pages/article_page.html: '//code.jquery.com/jquery-1.12.2.min.js' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
```

I think it has to do with overriding a template by extending itself.

For example, this template: https://github.com/ludrao/django-tellme/blob/afe8795053d8d4435e5aee8a9127f06ccaf25040/tellme/templates/tellme/js_inc.html#L5

In the project running compress, that template is overriden to suppress the jquery output like this:

```
{% extends 'tellme/js_inc.html' %}

{# remove jquery as it is included globally #}
{% block jquery %}{% endblock %}
```

However, compress doesn't seem to pick up the overriden template first.

Does this help?  If it isn't clear, I am describing the case that [django-overextends](https://github.com/stephenmcd/django-overextends) was designed for before it was handled by django

**Comment by thenewguy** [comment]
Not sure what is going on but I've not been able to reproduce this in a test case so I am going to close for now.
