### ISSUE TITLE
Offline compression breakage with COMPRESS_OFFLINE_CONTEXT as a generator

### ISSUE THREAD

**Issue by yesyves** [django-compressor/django-compressor#1091]
Hi

I have been using compressor for a while but I get this error following the update to v.3.0 (Django 3.2.10) :
```
Compressing... Traceback (most recent call last):
  File "/Users/yves/Desktop/passages/manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 294, in handle
    self.handle_inner(**options)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 317, in handle_inner
    offline_manifest, block_count, results = self.compress(engine, extensions, verbosity, follow_links, log)
  File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 234, in compress
    (len(offline_manifest), nodes_count, len(contexts)))
TypeError: object of type 'generator' has no len()
```

My settings :
```
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_CONTEXT = 'config.views.offline_context'
COMPRESS_FILTERS = {
    'css': ['compressor.filters.css_default.CssAbsoluteFilter',
            'compressor.filters.cssmin.rCSSMinFilter'],
    'js': ['compressor.filters.jsmin.JSMinFilter']
}
```

Thanks !

**Comment by carltongibson** [comment]
Hi @yesyves — Can I ask you for more detail here please? 

I'm running `compress` with Django 3.2.10 and `django-compressor` 3.0, on Python 3.10, without issue. 

Can you dig out this line: 

```
File "/Users/yves/.virtualenvs/passages/lib/python3.10/site-packages/compressor/management/commands/compress.py", line 234, in compress
    (len(offline_manifest), nodes_count, len(contexts)))
TypeError: object of type 'generator' has no len()
```

Presumably it's `contexts` that's the generator here? 🤔

(I'm wondering if you can create a sample project demonstrating the issue?)

**Comment by diox** [comment]
This is not related to your version of Django, but rather a regression with `COMPRESS_OFFLINE_CONTEXT` pointing to a generator. Likely from efb239da97f9f59b87a4a6715c477c64c781caf7

**Comment by diox** [comment]
(I also suspect it only happens when `compress` is verbose)

**Comment by yesyves** [comment]
Hi

Thanks for the follow-ups

offline_context() was missing from my report : 

```
LANGUAGES = [
    ('en', 'English'),
    ('fr-ca', 'Français (Canada)'),
    ('fr-fr', 'Français (France)'),
]

def offline_context():
    """
    Generate COMPRESS_OFFLINE_CONTEXT
    :return: context:[{}]
    """
    for code, description in settings.LANGUAGES:
        for base in ('base', 'print/print'):
            yield {'app_version': __version__,
                   'base_template': f'{base}.html',
                   'LANGUAGE_CODE': code,
                   'STATIC_URL': settings.STATIC_URL}
```

The lines in compress.py:232-235  

```
        if verbosity >= 1:
            log.write("done\nCompressed %d block(s) from %d template(s) for %d context(s).\n" %
                      (len(offline_manifest), nodes_count, len(contexts)))
        return offline_manifest, len(offline_manifest), offline_manifest.values()
```

And indeed `python manage.py compress -v 0` works OK

My question right now is mostly to know if my code which worked OK until 2.4.1 is causing the fault or if it is a v3.0 problem ?

**Comment by yesyves** [comment]
Don't know if that can help  :
```
print(offline_manifest)
print(nodes_count)
print(contexts)
```


```
OrderedDict([('eaf286ddc8f8f627bd5aa192fafc94d5616838118690660c213959d976297376', '<link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.262821893c77.css" type="text/css">'), ('0ff473a363664d01e3ef1c7d29f6a8bd9e37ed01d51ccbbdc033b260ab322e16', '<script src="/__compressor_url_placeholder__/CACHE/js/output.714d83841691.js"></script>'), ('04c99aebb7751bcf3f932bd7960c08c1fbc70f58c8d87f6bfbcf01fd15bafada', '<script src="/__compressor_url_placeholder__/CACHE/js/output.43f1419e9133.js"></script>'), ('217dd68b1f725f4f231137d5edcb46d02e150bcac7b312d63d4825953e382397', '<script src="/__compressor_url_placeholder__/CACHE/js/output.01a356cd0074.js"></script>'), ('fb997a19b3d905c5646c7df53f4c0db2049a65f692dd68d585c796dea2802a0b', '<link rel="stylesheet" href="/__compressor_url_placeholder__/CACHE/css/output.0e30e522f63c.css" type="text/css">'), ('82ce07c5960bb242485fd1e0e780a314a30ad8a4d4cca40cfa813b4467ec99cb', '<script src="/__compressor_url_placeholder__/CACHE/js/output.b50c43bb0f37.js"></script>'), ('06487855d0ee796cb12dfcef254daeb68de8631aaa84fedbfbd479449d62eea0', '<script src="/__compressor_url_placeholder__/CACHE/js/output.b50c43bb0f37.js"></script>')])

336

<generator object offline_context at 0x109301af0>
```

**Comment by yesyves** [comment]
output of `python mange.py compress -v 3`
[compress.log](https://github.com/django-compressor/django-compressor/files/7721762/compress.log)

**Comment by diox** [comment]
This is a regression from 3.0 when `COMPRESS_OFFLINE_CONTEXT` is a generator.

**Comment by diox** [comment]
This should be fix on `develop` branch. Can you install it and test so that I can make a new release with it ? Thanks.

**Comment by yesyves** [comment]
Thanks ! I'm used to pip, so what is the best way to install the develop version ?

**Comment by diox** [comment]
`pip install git+https://github.com/django-compressor/django-compressor.git@develop` should work.

**Comment by yesyves** [comment]
Hi
The installation worked (v.3.1)
The comression worked too with default -v 1.
Thanks for the quick fix !

**Comment by diox** [comment]
Thanks for the feedback. I'll release an official 3.1 shortly.

**Comment by carltongibson** [comment]
Thanks both! 🎁
