### ISSUE TITLE
ModuleNotFoundError: No module named 'compressor'

### ISSUE THREAD

**Issue by joerude** [django-compressor/django-compressor#1127]
**settings.py**
``` python3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'top-secret'


DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'todos',  
    'compressor',  
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COMPRESS_ROOT = BASE_DIR / 'static'

COMPRESS_ENABLED = True

STATICFILES_FINDERS = ('compressor.finders.CompressorFinder',)

```

 % `python manage.py migrate`     
Traceback (most recent call last):
  File "/home/joerude/Desktop/django-htmx-tailwind/manage.py", line 22, in <module>
    main()
  File "/home/joerude/Desktop/django-htmx-tailwind/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/joerude/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/joerude/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/home/joerude/.local/lib/python3.10/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/joerude/.local/lib/python3.10/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/joerude/.local/lib/python3.10/site-packages/django/apps/config.py", line 228, in create
    import_module(entry)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'compressor'

I've already install package via `pip install django-compressor`

 > `pip install django_compressor`:
Requirement already satisfied: django_compressor in ./venv/lib/python3.10/site-packages (3.1)
Requirement already satisfied: django-appconf>=1.0.3 in ./venv/lib/python3.10/site-packages (from django_compressor) (1.0.5)
Requirement already satisfied: rjsmin==1.2.0 in ./venv/lib/python3.10/site-packages (from django_compressor) (1.2.0)
Requirement already satisfied: rcssmin==1.1.0 in ./venv/lib/python3.10/site-packages (from django_compressor) (1.1.0)
Requirement already satisfied: django in ./venv/lib/python3.10/site-packages (from django-appconf>=1.0.3->django_compressor) (4.0.3)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.10/site-packages (from django->django-appconf>=1.0.3->django_compressor) (0.4.2)
Requirement already satisfied: asgiref<4,>=3.4.1 in ./venv/lib/python3.10/site-packages (from django->django-appconf>=1.0.3->django_compressor) (3.5.2)

**Comment by adamzap** [comment]
@joerude Not sure if this is still an issue for you, but it looks like `~/.local` and `./venv` are different Python environments. Could that be the case?
