### ISSUE TITLE
4.1: Unable to run tests

### ISSUE THREAD

**Issue by dvzrv** [django-compressor/django-compressor#1143]
Hi! I'm packaging this project for Arch Linux.
I'm stuck upgrading the package to 4.1 as I am unable to run the tests:

```
python -m build --wheel --no-isolation
export PYTHONPATH="build:$PYTHONPATH"
django-admin test --settings=compressor.test_settings compressor
```

The above worked with 4.0, but now it yields

```
ERROR: test_template_precompiler (compressor.tests.test_parsers.LxmlParserTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/django/test/utils.py", line 460, in inner
    return func(*args, **kwargs)
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/tests/test_base.py", line 293, in test_template_precompiler
    output = make_soup(css_node.output('inline'))
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/css.py", line 46, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/css.py", line 48, in output
    return super().output(*args, **kwargs)
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/base.py", line 330, in output
    return self.handle_output(mode, filtered_output, forced, basename)
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/base.py", line 338, in handle_output
    return output_func(mode, content, forced, basename)
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/base.py", line 359, in output_inline
    return self.render_output(mode, {"content": content})
  File "/build/python-django-compressor/src/django_compressor-4.1/compressor/base.py", line 390, in render_output
    return render_to_string(template_name, context=final_context)
  File "/usr/lib/python3.10/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3.10/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3.10/site-packages/django/template/engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3.10/site-packages/django/template/engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/usr/lib/python3.10/site-packages/django/template/loaders/base.py", line 23, in get_template
    contents = self.get_contents(origin)
  File "/usr/lib/python3.10/site-packages/django/template/loaders/cached.py", line 26, in get_contents
    return origin.loader.get_contents(origin)
  File "/usr/lib/python3.10/site-packages/django/template/loaders/filesystem.py", line 22, in get_contents
    with open(origin.name, encoding=self.engine.file_charset) as fp:
OSError: [Errno 36] File name too long: '/build/python-django-compressor/src/django_compressor-4.1/compressor/tests/test_templates/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/basic/test_block_super_base_compressed/test_block_super_base_compressed/test_block_super_base_compressed
/test_block_super_base_compressed/test_block_super_base_compressed/test_block_super_base_compressed/test_block_super_multiple_cached/test_block_super_multiple_cached/test_block_super_multiple_cached/test_block_super_multiple_cached/test_block_super_multiple_cached/test_block_super_multiple_cached/test_block_super_mult
iple/test_block_super_multiple/test_block_super_multiple/test_block_super_multiple/test_block_super_multiple/test_block_super_multiple/test_block_super/test_block_super/test_block_super/test_block_super/test_block_super/test_block_super/test_block_super_extra/test_block_super_extra/test_block_super_extra/test_block_su
per_extra/test_block_super_extra/test_block_super_extra/test_complex/test_complex/test_complex/test_complex/test_complex/test_complex/test_condition/test_condition/test_condition/test_condition/test_condition/test_condition/basic/basic/basic/basic/basic/basic/test_extends_recursion/test_extends_recursion/test_extends_
recursion/test_extends_recursion/test_extends_recursion/test_extends_recursion/test_extends_relative/test_extends_relative/test_extends_relative/test_extends_relative/test_extends_relative/test_extends_relative/test_inline_non_ascii/test_inline_non_ascii/test_inline_non_ascii/test_inline_non_ascii/test_inline_non_asci
i/test_inline_non_ascii/test_duplicate/test_duplicate/test_duplicate/test_duplicate/test_duplicate/test_duplicate/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_url_independence/test_static_url_independence/tes
t_static_url_independence/test_static_url_independence/test_static_url_independence/test_static_url_independence/test_templatetag_named/test_templatetag_named/test_templatetag_named/test_templatetag_named/test_templatetag_named/test_templatetag_named/test_templatetag/test_templatetag/test_templatetag/test_templatetag/
test_templatetag/test_templatetag/test_error_handling/test_error_handling/test_error_handling/test_error_handling/test_error_handling/test_error_handling/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/tes
t_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_contex
t/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_context_super/test_with_c
ontext_super/test_with_context_super/test_with_context_super/test_with_context_variable_inheritance/test_with_context_variable_inheritance/test_with_context_variable_inheritance/test_with_context_variable_inheritance/test_with_context_variable_inheritance/test_with_context_variable_inheritance/test_with_context_variab
le_inheritance_super/test_with_context_variable_inheritance_super/test_with_context_variable_inheritance_super/test_with_context_variable_inheritance_super/test_with_context_variable_inheritance_super/test_with_context_variable_inheritance_super/test_error_handling/test_error_handling/test_error_handling/test_error_ha
ndling/test_error_handling/test_error_handling/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_static_templatetag/test_compress_command/test_compress_command/test_compress_command/test_compress_command/test_compress_command/test_compress_comm
and/test_compress_command/compressor/css_inline.html'

----------------------------------------------------------------------
Ran 509 tests in 0.871s

FAILED (errors=307, skipped=1)
Destroying test database for alias 'default'...
```

Full build log: 
[python-django-compressor-4.1-1-x86_64-build.log](https://github.com/django-compressor/django-compressor/files/9404211/python-django-compressor-4.1-1-x86_64-build.log)
Full check log:
[python-django-compressor-4.1-1-x86_64-check.log](https://github.com/django-compressor/django-compressor/files/9404214/python-django-compressor-4.1-1-x86_64-check.log)

**Comment by carltongibson** [comment]
Hi @dvzrv — I'm struggling to reproduce. I'm guessing it's something about your environment. 🤔

Are you able to `git bisect` the possible regression? Or help us pin down a reproduce? 
Thanks.

**Comment by dvzrv** [comment]
I've just checked with 4.0 and also 3.1. They now all exhibit this problem!

It seems the problems lie elsewhere and I'm suspecting either of those (currently in use on Arch Linux):

python-coverage 6.1.1 (unlikely)
jinja2 3.1.2 (likely?)
django 4.0.6 (unlikely, as you test against it in CI)
django-sekizai 4.0.0 (likely)

**Comment by dvzrv** [comment]
Yep, seems jinja2 in version > 3.0.3 breaks your tests.

**Comment by dvzrv** [comment]
From the log:

```
ERROR: test_deleting_manifest_does_not_affect_rendering (compressor.tests.test_offline.OfflineCompressBasicTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-django-compressor/src/django_compressor-4.1/test_dir/usr/lib/python3.10/site-packages/compressor/tests/test_offline.py", line 148, in setUp
    jinja2_env = override_settings['COMPRESS_JINJA2_GET_ENVIRONMENT']()
  File "/build/python-django-compressor/src/django_compressor-4.1/test_dir/usr/lib/python3.10/site-packages/compressor/tests/test_offline.py", line 127, in <lambda>
    lambda: self._get_jinja2_env())
  File "/build/python-django-compressor/src/django_compressor-4.1/test_dir/usr/lib/python3.10/site-packages/compressor/tests/test_offline.py", line 251, in _get_jinja2_env
    jinja2.ext.with_,
AttributeError: module 'jinja2.ext' has no attribute 'with_'
```

**Comment by diox** [comment]
That's https://github.com/django-compressor/django-compressor/issues/1139

**Comment by dvzrv** [comment]
I'll close this ticket in favor of the other!
