### ISSUE TITLE
TypeError: inner() missing 1 required positional argument: 'request'

### ISSUE THREAD

**Issue by lihuacai168** [django-compressor/django-compressor#1155]
# django version
`Django=2.2.17`
#  django-compressor version
`django-compressor=4.1`
# settings.py
```python
INSTALLED_APPS = [
    'compressor',
    "simpleui",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]
MIDDLEWARE = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'compressor.finders.CompressorFinder',
]

STATIC_URL = "/static/"

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder'
]

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
COMPRESS_ROOT = os.path.join(BASE_DIR, 'static')

```

# error
```shell
Traceback (most recent call last):
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 104, in run
    self.inner_run(None, **options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/Users/rikasai/.pyenv/versions/3.9.11/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/rikasai/code/python/FasterRunner/FasterRunner/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 135, in __init__
    self.load_middleware()
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/core/handlers/base.py", line 37, in load_middleware
    mw_instance = middleware(handler)
  File "/Users/rikasai/.virtualenvs/fast39/lib/python3.9/site-packages/django/contrib/staticfiles/finders.py", line 215, in __init__
    self.storage = self.storage()
TypeError: inner() missing 1 required positional argument: 'request'

```

**Comment by bcail** [comment]
@lihuacai168 could you try your application with a more recent `django` and `django-compressor`, and see if the problem persists?

**Comment by lihuacai168** [comment]
> with

Sorry, I no longer use `django-compressor`
