### ISSUE TITLE
Does not reload cache when @import less files are changed in development

### ISSUE THREAD

**Issue by issackelly** [django-compressor/django-compressor#274]
It's pretty straightforward

template.html

```
{% compress css %}
    <link rel="stylesheet" href="{{ STATIC_URL }}less/bootstrap.less" type="text/less" />
{% endcompress %}
```

bootstrap.less

```
...
// Custom classes for Nebula. Stylesheet.less will keep getting smaller until we have as little customization as possible.
@import "_stylesheet.less";
```

If I make a change in _stylesheet.less, I have to restart runserver to see the change. compress doesn't do it automatically.

I know that there are several ways around this, it's just a bug I encountered.

Here are my settings

```
>>> from django.conf import settings
>>> settings
<django.conf.LazySettings object at 0x10842e1d0>
>>> settings.COMPRESS
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/issackelly/.virtualenvs/nebula/lib/python2.7/site-packages/django/utils/functional.py", line 277, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'COMPRESS'
>>> settings.COMPRES
KeyboardInterrupt
>>> settings.COMPRESS_OFFLINE
False
>>> settings.COMPRESS_ENABLED
True
>>> settings.COMPRESS_URL
'/static/'
>>> settings.COMPRESS_PARSER
'compressor.parser.LxmlParser'
>>> settings.COMPRESS_PRECOMPILERS
(('text/less', 'lessc {infile} {outfile}'),)
>>> 
```

**Comment by k-funk** [comment]
I think that this [PR](https://github.com/django-compressor/django-compressor/pull/289#issuecomment-220747098)'s solution is best because:

1. We still only define file dependencies in one place [(this concern)](https://github.com/django-compressor/django-compressor/issues/274#issuecomment-13620163).
2. All files listed within blocks that have the `group_first=true` flag will get watched, and the group will recompile on change, so that server restart isn't required (OP's concern).
3. It's optional — won't break anything going forward.
4. Filter's don't need to require any changes to make them work.

The only downside is that other `@import`'s within defined dependencies won't be caught when modified. However, I like this problem better than the current one:

- I can't use `variables.scss`, `mixins.scss`, `....scss` that all other files depend on
- A server that doesn't notice/pickup file changes because they were `@import`ed
