### ISSUE TITLE
CommandError: An error occured during rendering xxxxxxxxxx 'ascii' codec can't decode byte 0xe5 in position 12735: ordinal not in range(128)

### ISSUE THREAD

**Issue by bearmingo** [django-compressor/django-compressor#495]
I use compressor with less file. When .less file container chinese words, it will report Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 222, in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 255, in execute
    output = self.handle(_args, *_options)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/base.py", line 385, in handle
    return self.handle_noargs(*_options)
  File "/usr/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 342, in handle_noargs
    self.compress(sys.stdout, *_options)
  File "/usr/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 281, in compress
    "%s" % (template.template_name, e))
CommandError: An error occured during rendering /home/cgm/services/mymenu/apps/templates/base/base.html: 'ascii' codec can't decode byte 0xe5 in position 12735: ordinal not in range(128)

**Comment by karyon** [comment]
looks like a duplicate of #611.

**Comment by karyon** [comment]
...or of #429 :)

**Comment by bearmingo** [comment]
:) The reason for this exception is that `lessc` is not in my bash's path. I think the exception information  is not useful to help to find this real reason. If the execption prompt it, it will be very helpful

**Comment by karyon** [comment]
...your lessc was not in your path but django-compressor crashed only when there were chinese characters in your less files...?

**Comment by bearmingo** [comment]
Yeah,  Follow is the exception stack.
`  File "E:\Projects\work\env\lib\site-packages\compressor\css.py", line 49, in o
utput
    ret.append(subnode.output(*args, **kwargs))
  File "E:\Projects\work\env\lib\site-packages\compressor\css.py", line 51, in o
utput
    return super(CssCompressor, self).output(*args, **kwargs)
  File "E:\Projects\work\env\lib\site-packages\compressor\base.py", line 292, in
 output
    output = '\n'.join(self.filter_input(forced))
  File "E:\Projects\work\env\lib\site-packages\compressor\base.py", line 232, in
 filter_input
    for hunk in self.hunks(forced):
  File "E:\Projects\work\env\lib\site-packages\compressor\base.py", line 204, in
 hunks
    precompiled, value = self.precompile(value, **options)
  File "E:\Projects\work\env\lib\site-packages\compressor\base.py", line 265, in
 precompile
    return True, filter.input(**kwargs)
  File "E:\Projects\work\env\lib\site-packages\compressor\filters\base.py", line
 229, in input
    return super(CachedCompilerFilter, self).input(**kwargs)
  File "E:\Projects\work\env\lib\site-packages\compressor\filters\base.py", line
 184, in input
    filtered, err = filtered.decode(encoding), err.decode(encoding)
  File "E:\Projects\work\env\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb2 in position 8: invalid s
tart byte`

**Comment by karyon** [comment]
well, this is a different error that the one in your original post. what did you change to get the different ones? or is it the same setup with a new version of django-compressor?

also, could you post the .less-file you were using?

btw i'm amazed that you're responding two and a half years later, nice :)

**Comment by bearmingo** [comment]
Sorry, last project is cancelled, so I forgot it. Recently I Start other project, also using this helpful library and I receive email notification last day. :）
I think maybe this the same problem.
my code is:
```
{% block extracss %}
  <link rel="stylesheet" type="text/less" href="{% static "account/css/account.less" %}"/>
{% endblock extracss %}
```
[account.txt](https://github.com/django-compressor/django-compressor/files/564278/account.txt)

**Comment by karyon** [comment]
hey, it doesn't seem like there is any non-ascii characters in that file...?

**Comment by bearmingo** [comment]
This issue happen in my windows development, and system language is Chinese. I think when comressor run a command failed, it will get a error with chinese words. This words will be encoding by cp936. But the compressor parser as UTF8

**Comment by karyon** [comment]
i'm sorry but it's still unclear to me what the problem is. the account.txt you posted and the template code do not contain any non-ascii characters and should be no problem for any conversion. could you try to explain again where the chinese words that might be the problem come from?

**Comment by bearmingo** [comment]
I mean The non-ASCII do not come from my less code file, but from my OS. When the lessc is not in path, cmd will output
'''
"less 不是内部命令或者外部命令"
'''

**Comment by karyon** [comment]
aaaaaaah now i get it. thanks for staying with me :)
