### ISSUE TITLE
Error when running testes: 'OfflineGenerationError'

### ISSUE THREAD

**Issue by mauricioabreu** [django-compressor/django-compressor#579]
I am facing the following error when running my test suite.

`python manage.py test`

It looks like code is raising an error but Django compressor is raising its own error before I can see what really caused it.

```
Traceback (most recent call last):
  File "/vagrant/apps/user/tests/test_views.py", line 220, in test_edit_user_without_permission
    response = self.client.get(url)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/client.py", line 473, in get
    response = super(Client, self).get(path, data=data, **extra)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/client.py", line 280, in get
    return self.request(**r)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/client.py", line 426, in request
    response = self.handler(environ)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/client.py", line 109, in __call__
    response = self.get_response(request)
  File "/vagrant/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 194, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/vagrant/env/lib/python2.6/site-packages/django/core/handlers/base.py", line 236, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/vagrant/env/lib/python2.6/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/vagrant/env/lib/python2.6/site-packages/django/views/defaults.py", line 46, in server_error
    return http.HttpResponseServerError(template.render(Context({})))
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/test/utils.py", line 85, in instrumented_test_render
    return self.nodelist.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/vagrant/env/lib/python2.6/site-packages/django/template/base.py", line 854, in render_node
    return node.render(context)
  File "/vagrant/env/lib/python2.6/site-packages/compressor/templatetags/compress.py", line 147, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/vagrant/env/lib/python2.6/site-packages/compressor/templatetags/compress.py", line 88, in render_compressed
    cached_offline = self.render_offline(context, forced=forced)
  File "/vagrant/env/lib/python2.6/site-packages/compressor/templatetags/compress.py", line 72, in render_offline
    'You may need to run "python manage.py compress".' % key)
OfflineGenerationError: You have offline compression enabled but key "65ebfa60a748f7c943382cac79e2bd6d" is missing from offline manifest. You may need to run "python manage.py compress".
```

**Comment by carltongibson** [comment]
The error begins with your test: `test_edit_user_without_permission`. This will be rendering a page. Presumably that contains a `compress` tag. 

Either run compress before testing or don't enable offline compression. — That should fix it.

**Comment by carltongibson** [comment]
@diox To close, can reopen if needed.

**Comment by diox** [comment]
Thanks.

**Comment by mauricioabreu** [comment]
Thank you! Gonna try that.
