### ISSUE TITLE
Failed manage.py on PyCharm with parser error

### ISSUE THREAD

**Issue by Jonybang** [django-compressor/django-compressor#620]
When I prime this: "Tools">"Run manage.py Task" I get in console:
```
Failed to get real commands on module "eva-events": python process died with code 1: Traceback (most recent call last):
  File "C:\Other programs\PyCharm 4.5.1\helpers\pycharm\manage_tasks_provider.py", line 22, in <module>
    parser.report_data(dumper)
  File "C:\Other programs\PyCharm 4.5.1\helpers\pycharm\django_manage_commands_provider\_parser\parser.py", line 40, in report_data
    module_to_use.process_command(dumper, command, command.create_parser("", command_name))
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 312, in create_parser
    help='Verbosity level; 0=minimal output, 1=normal output, 2=verbose output, 3=very verbose output')
  File "C:\Python27\lib\optparse.py", line 1018, in add_option
    raise TypeError, "invalid arguments"
TypeError: invalid arguments
```
When I don't load django-compressor I'm not getting this message
Settings:
```
INSTALLED_APPS = (
    ...
    'compressor',
    'bootstrap3',
    'bootstrap3_sass',
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)
```
But the project is launched, everything works fine except manage.py.
requirements.txt:
```
Django==1.8.2
SQLAlchemy==1.0.4
dj-database-url==0.3.0
django-appconf==1.0.1
django-bootstrap3==5.4.0
django-bootstrap3-sass==3.3.2.2
django-compressor==1.5
django-libsass==0.3
django-postgrespool==0.3.0
gunicorn==19.3.0
libsass==0.8.2
psycopg2==2.6
six==1.9.0
whitenoise==1.0.6
```
PyCharm ver: 4.5.1

**Comment by diox** [comment]
Hi,

From http://stackoverflow.com/questions/30403806/pycharm-cant-open-manage-py-task it looks like it's an issue with PyCharm, I recommend opening an issue there.

**Comment by zhangxuwei0801** [comment]
Hi, I can know you is how to solve this problems? I got the same problems. Thanks

**Comment by s8435330song** [comment]
same question waiting for solving....

**Comment by s8435330song** [comment]
I finally solved this problem with changing python version from 2.7 to 2.7.5.
I don't why, and I just change the code from one server to another one. I copy the environment of the server working normally
