### ISSUE TITLE
Extra slashes work in DEBUG mode but break in production

### ISSUE THREAD

**Issue by WoLpH** [django-compressor/django-compressor#666]
As discussed in #553, when having a static declaration such as this: `{% static '/some_file.js' %}` the module will break with a `SuspiciousOperation` on production. While this is not a bad thing, it does work fine when `DEBUG = True`.

I propose that this either gives the same error when `DEBUG` is enabled or that extra slashes be collapsed into a single one. Having code that breaks in production while working fine in development can be a pain to debug.

**Comment by carltongibson** [comment]
Can you post a traceback showing exactly where this arrises? 

I'm inclined to say this is just a usage error. ([RFC 2396](http://www.ietf.org/rfc/rfc2396.txt) has a single slash as the path component separator.) But having different behaviour based on the value of DEBUG is, I can see, going to be a pain.

**Comment by WoLpH** [comment]
I agree with you about the usage error, while most software (and websites) accept multiple slashes, if it can be avoided it should be. The only thing that really bugs me here is that code breaks in production while working perfectly in development, that can be quite dangerous


There are two cases naturally so here's the stacktrace for both.

First, using the `STATIC_URL` setting (this one is particularly unclear):
**Template:**
```
{% compress js %}
<script type="text/javascript" src="{{ STATIC_URL }}/js/jquery-1.10.1.min.js"></script>
{% endcompress %}
```
**Stacktrace:**
```
Traceback (most recent call last):
  File "django/core/handlers/base.py", line 148, in get_response
    response = callback(request, **param_dict)
  File "django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "django/views/defaults.py", line 21, in page_not_found
    return http.HttpResponseNotFound(t.render(RequestContext(request, {'request_path': request.path})))
  File "django/template/base.py", line 140, in render
    return self._render(context)
  File "django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "compressor/cache.py", line 104, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "compressor/base.py", line 178, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "compressor/base.py", line 172, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "compressor/js.py", line 20, in split_contents
    filename = self.get_filename(basename)
  File "compressor/base.py", line 124, in get_filename
    filename = self.storage.path(basename)
  File "django/core/files/storage.py", line 245, in path
    raise SuspiciousOperation("Attempted access to '%s' denied." % name)
SuspiciousOperation: Attempted access to '/js/jquery-1.10.1.min.js' denied.
```
---

Secondly, using the static templatetag:
**Template:**
```
{% compress js %}
<script type="text/javascript" src="{% static '/js/jquery-1.10.1.min.js' %}"></script>
{% endcompress %}
```
**Stacktrace:**
```
Traceback (most recent call last):
  File "django/core/handlers/base.py", line 134, in get_response
    response = response.render()
  File "django/template/response.py", line 104, in render
    self._set_content(self.rendered_content)
  File "django/template/response.py", line 81, in rendered_content
    content = template.render(context)
  File "django/template/base.py", line 140, in render
    return self._render(context)
  File "django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "django/template/base.py", line 823, in render
    bit = self.render_node(node, context)
  File "django/template/debug.py", line 74, in render_node
    return node.render(context)
  File "compressor/templatetags/compress.py", line 149, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "compressor/templatetags/compress.py", line 102, in render_compressed
    cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
  File "compressor/templatetags/compress.py", line 81, in render_cached
    cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "compressor/cache.py", line 104, in get_templatetag_cachekey
    "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "compressor/base.py", line 178, in cachekey
    [self.content] + self.mtimes).encode(self.charset), 12)
  File "compressor/utils/decorators.py", line 39, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "compressor/base.py", line 172, in mtimes
    for kind, value, basename, elem in self.split_contents()
  File "compressor/js.py", line 19, in split_contents
    basename = self.get_basename(attribs['src'])
  File "compressor/base.py", line 89, in get_basename
    "compressed" % (url, base_url))
UncompressableFileError: '/js/jquery-1.10.1.min.js' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed
```

**Comment by carltongibson** [comment]
The second case is a different error. Does that (too) only occur in production?

**Comment by carltongibson** [comment]
Also, what versions of Django and compressor are you using? (My line numbers aren't matching yours.)

**Comment by carltongibson** [comment]
Your second example is just the behaviour of `urljoin`:

```
>>> from urlparse import urljoin
>>> base = '/static/'
>>> urljoin(base, 'endpoint')
'/static/endpoint'
>>> urljoin(base, '/endpoint')
'/endpoint'
```

**Comment by WoLpH** [comment]
Sorry, should have mentioned the versions:
Django 1.4.22
Django Compressor 1.5

In both cases I only see these errors when `DEBUG` is not enabled, the latter case doesn't actually work properly when using debug settings however. As you pointed out it will join them and thereby breaking the url. Still, an explicit warning would be better :)

**Comment by carltongibson** [comment]
OK. Both of these are too far down the stack to be compressor issues. You're looking at _Django's_ `static` template tag and `utils._os.safe_join`. If you need a _fix_ you'll need to take it up there.

**Comment by WoLpH** [comment]
I have to disagree, without compressor at least the first one works fine both in production and development, since compressor is parsing them anyhow the least it could do is warn about potential errors.

**Comment by carltongibson** [comment]
You're welcome to suggest a specific fix in the form of a pull request. If it's simple enough it may be something we can add — but reimplementing difficult logic that Django itself handles (such as path sanitisation) isn't something we're going to add.

**Comment by WoLpH** [comment]
I don't think it's that complex actually, this is (what I gather from the source) simply about calling the parser in all cases instead of just when debug is not enabled.

Essentially, if statements like these should have a (by default enabled) flag to parse the script tags even when DEBUG is true: https://github.com/django-compressor/django-compressor/blob/develop/compressor/templatetags/compress.py#L94-L96

**Comment by carltongibson** [comment]
You're welcome to enable these in your settings. Failing that a PR resolving this simply would be kindly reviewed.
