### ISSUE TITLE
TypeError: coercing to unicode in Django 1.9

### ISSUE THREAD

**Issue by skyflyer** [django-compressor/django-compressor#717]
When running `./manage.py compress` on Django 1.9 installation, I'm getting the following error. The error is not present on Django 1.8.6. Also note the deprecation warnings.

```
/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/base.py:577: RemovedInDjango110Warning: NoArgsCommand class is deprecated and will be removed in Django 1.10. Use BaseCommand instead, which takes no arguments by default.
  RemovedInDjango110Warning

/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/base.py:265: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  RemovedInDjango110Warning)

Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/project/path/virtualenv/lib/python2.7/site-packages/django/core/management/base.py", line 584, in handle
    return self.handle_noargs(**options)
  File "/project/path/virtualenv/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 302, in handle_noargs
    self.compress(sys.stdout, **options)
  File "/project/path/virtualenv/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 162, in compress
    followlinks=options.get('followlinks', False)):
  File "/project/path/virtualenv/lib/python2.7/os.py", line 278, in walk
    names = listdir(top)
TypeError: coercing to Unicode: need string or buffer, Origin found
```

**Comment by diox** [comment]
Hi,

Please try again with the current develop branch, thanks.

**Comment by brandoncazander** [comment]
@diox I can confirm that the current develop branch (cloned at 199089e1ed9adbd5c5ef6bf2f6e0445c579495b1) fixed this TypeError for me.

**Comment by skyflyer** [comment]
@diox as @brandoncazander commented, it works for me as well, so I'm closing this issue. Thanks for the quick response.

**Comment by altryne** [comment]
Sorry to ask to re-open this. 
Tried to install 1.6 and still happens. Installing from develop branch, this goes away.
Was the fix of this somehow missed in 1.6?

**Comment by karyon** [comment]
@altryne django 1.9 came into the development branch after compressor 1.6 was released. so i'd expect exactly what you described.

django-compressor 2.0 has been released a few days ago, go check that out! :)

**Comment by altryne** [comment]
thanx @karyon !
