### ISSUE TITLE
Recursion error when extending Django admin templates and compressing offline

### ISSUE THREAD

**Issue by chriskief** [django-compressor/django-compressor#718]
Compressor throws a recursion error when trying to compress offline and admin extension templates are present:

```
$ python /www/360i/artifact/manage.py compress

Traceback (most recent call last):
  File "/www/360i/artifact/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/www/360i/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 286, in handle
    self.compress(sys.stdout, **options)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 181, in compress
    nodes = list(parser.walk_nodes(template))
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 150, in walk_nodes
    for node in self.walk_nodes(node, original):
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 146, in walk_nodes
    for node in self.get_nodelist(node, original):
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 128, in get_nodelist
    return handle_extendsnode(node, block_context=None, original=original)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 41, in handle_extendsnode
    return handle_extendsnode(node, block_context, original)
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 41, in handle_extendsnode
    return handle_extendsnode(node, block_context, original)
  { ... CONTINUED ... }
  File "/www/360i/local/lib/python2.7/site-packages/compressor/offline/django.py", line 30, in handle_extendsnode
    context = Context()
  File "/www/360i/local/lib/python2.7/site-packages/django/template/context.py", line 151, in __init__
    self.render_context = RenderContext()
  File "/www/360i/local/lib/python2.7/site-packages/django/template/context.py", line 34, in __init__
    self._reset_dicts(dict_)
RuntimeError: maximum recursion depth exceeded
```

This is due to the template extending a template that isn't defined in the application (admin/base_site.html is in [django.contrib.admin.templates] (https://github.com/django/django/tree/master/django/contrib/admin/templates/admin)):

```django
{% extends "admin/base_site.html" %}

{% block title %}360i{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">360i</a></h1>
{% endblock %}
```

Perhaps I missed a way to tell compressor to ignore certain templates?

**Comment by cbjadwani** [comment]
Does it work with compressor disabled? This can happen due to template name conflict - for example http://stackoverflow.com/questions/25263277/django-template-extending-itself-maximum-recursion-depth-exceeded-when-trying-t

**Comment by chriskief** [comment]
Yes, everything works correctly with compressor disabled.

If I remove these templates, offline compression works properly (manage.py compress).

My current workaround in my build script is to move these admin templates out of my templates directory, run compress and then copy them back.

**Comment by yprez** [comment]
Having the same issue with offline compression.

Seems to happen if a template is overriding and extending a template with the same name, for example `{% extends "admin/index.html" %}` in `admin/index.html` itself.
