### ISSUE TITLE
Hard to debug error

### ISSUE THREAD

**Issue by nordbit** [django-compressor/django-compressor#763]
Any hint?
```
$ python manage.py compress --force
/srv/python35/lib/python3.5/site-packages/django/utils/six.py:808: RemovedInDjango110Warning: SubfieldBase has been deprecated. Use Field.from_db_value instead.
  return meta(name, bases, d)

/srv/python35/lib/python3.5/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

Traceback (most recent call last):
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 883, in _resolve_lookup
    current = current[bit]
  File "/srv/python35/lib/python3.5/site-packages/django/template/context.py", line 77, in __getitem__
    raise KeyError(key)
KeyError: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 889, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'Context' has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 898, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/python35/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/python35/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/python35/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/python35/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/python35/lib/python3.5/site-packages/compressor/management/commands/compress.py", line 286, in handle
    self.compress(sys.stdout, **options)
  File "/srv/python35/lib/python3.5/site-packages/compressor/management/commands/compress.py", line 181, in compress
    nodes = list(parser.walk_nodes(template))
  File "/srv/python35/lib/python3.5/site-packages/compressor/offline/django.py", line 150, in walk_nodes
    for node in self.walk_nodes(node, original):
  File "/srv/python35/lib/python3.5/site-packages/compressor/offline/django.py", line 146, in walk_nodes
    for node in self.get_nodelist(node, original):
  File "/srv/python35/lib/python3.5/site-packages/compressor/offline/django.py", line 128, in get_nodelist
    return handle_extendsnode(node, block_context=None, original=original)
  File "/srv/python35/lib/python3.5/site-packages/compressor/offline/django.py", line 34, in handle_extendsnode
    compiled_parent = extendsnode.get_parent(context)
  File "/srv/python35/lib/python3.5/site-packages/django/template/loader_tags.py", line 134, in get_parent
    parent = self.parent_name.resolve(context)
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 730, in resolve
    arg_vals.append(arg.resolve(context))
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 850, in resolve
    value = self._resolve_lookup(context)
  File "/srv/python35/lib/python3.5/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [request] in "[{'True': True, 'None': None, 'False': False}]"
```

Python==3.5.1, django==1.9.6, django-compressor==2.0

**Comment by karyon** [comment]
no idea what that is... can you provide more contexts like your settings and what code triggers this.

**Comment by nordbit** [comment]
Same me. I switched for now to django-pipeline. Probably somwhere in template code I have a bug. But project is big, more than 20 apps. I hate the moment in django, where debburger do not show part of code or file which generates an error.

**Comment by karyon** [comment]
i'm sorry that django-compressor failed you :(

closing, not enough information.

**Comment by guhuajun** [comment]
@nordbit You may add -v3 to get verbose messages. I am ecountering this issue too.

![default](https://cloud.githubusercontent.com/assets/14121694/23602136/d9449168-0289-11e7-8199-5f0dc2239400.png)

https://github.com/django-compressor/django-compressor/issues/785 may be a walkaround for this.
