### ISSUE TITLE
Support for django-storages S3Boto3Storage backend?

### ISSUE THREAD

**Issue by jameshiew** [django-compressor/django-compressor#808]
I'm following along with the docs at http://django-compressor.readthedocs.io/en/latest/remote-storages/#django-storages . boto was uploading to S3 too slowly for some reason, so I substituted the boto backend for the boto3 backend. `./manage.py collectstatic` worked and uploaded everything at a decent speed - but then when trying to access the index page of my site, I get the following error:

```
Traceback (most recent call last):
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 170, in __call__
    response = self.get_response(request)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = response_for_exception(request, exc)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 86, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 135, in handle_uncaught_exception
    return callback(request, **param_dict)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/views/defaults.py", line 74, in server_error
    return http.HttpResponseServerError(template.render())
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 127, in render
    return self.render_compressed(context, self.kind, self.mode, forced=forced)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/templatetags/compress.py", line 103, in render_compressed
    rendered_output = compressor.output(mode, forced=forced)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/css.py", line 49, in output
    ret.append(subnode.output(*args, **kwargs))
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/css.py", line 51, in output
    return super(CssCompressor, self).output(*args, **kwargs)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/base.py", line 299, in output
    return self.handle_output(mode, filtered_output, forced)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/base.py", line 307, in handle_output
    return output_func(mode, content, forced, basename)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/compressor/base.py", line 318, in output_file
    if not self.storage.exists(new_filepath) or forced:
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 475, in exists
    if self.entries:
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 312, in entries
    for entry in self.bucket.objects.filter(prefix=self.location))
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/storages/backends/s3boto3.py", line 311, in <genexpr>
    self._entries = dict((self._decode_name(entry.key), entry)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/boto3/resources/collection.py", line 166, in pages
    for page in pages:
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/paginate.py", line 102, in __iter__
    response = self._make_request(current_kwargs)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/paginate.py", line 174, in _make_request
    return self._method(**current_kwargs)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/client.py", line 513, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/client.py", line 566, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/abcxyz/.abcxyz/local/lib/python2.7/site-packages/botocore/validate.py", line 270, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "prefix", must be one of: Bucket, Delimiter, EncodingType, Marker, MaxKeys, Prefix, RequestPayer
```

Relevant settings snippet
```python
AWS_ACCESS_KEY_ID = '...'
AWS_SECRET_ACCESS_KEY = '...'
AWS_STORAGE_BUCKET_NAME = 'my-bucket-abcxyz'
AWS_QUERYSTRING_AUTH = False
AWS_PRELOAD_METADATA = True  # for collectfast to work
STATIC_URL = COMPRESS_URL = 'https://{}.s3.amazonaws.com/'.format(AWS_STORAGE_BUCKET_NAME)
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
COMPRESS_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
```

This is using Python 2.7.6 and Django 1.10.1.

**Comment by karyon** [comment]
did the `S3BotoStorage` essentially work or did it have problems besides slow uploads?

if it worked, i'd guess there is some incompatibility with the new backend. unfortunately, it seems like the S3Boto3Storage backend is completely undocumented. so there is no info on what the differences between the backends could be and i have no way to test this, so i hate to say it but you're on your own... :( any additional information or workarounds you post here would be appreciated.

**Comment by karyon** [comment]
opened https://github.com/jschneier/django-storages/issues/229. @jameshiew, do you think this issue might actually be in django-storages? i mean there was no code specific to that boto backend involved on your or django-compressor's side involved, and you simply switched backends, i don't know whether there is anything that django-compressor could fix...

**Comment by jameshiew** [comment]
S3BotoStorage essentially worked, it was just slow and kept failing on uploading one file. I think this issue might be related - https://github.com/boto/boto/issues/2207 , as this is the error I got when a S3 file upload failed. Yes, this issue as a whole may be better fixed in the django-storages project. Unfortunately it's unlikely I'll be able to contribute in any meaningful way to fixing this issue in the near future, but I'll post updates here if I find anything else out.

**Comment by karyon** [comment]
it looks like there is nothing i can do, and it seems likely the bug is in the boto3 backend. if you find anything new, or something happens in the django-storages issue i opened, lets have a look at this issue here again.
