### ISSUE TITLE
Offline compressions crashes if no 'compress' tags exist

### ISSUE THREAD

**Issue by mistalaba** [django-compressor/django-compressor#818]
Ran in to this issue whan doing my latest depoyment:

> Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 291, in handle
    self.compress(sys.stdout, **options)
  File "/home/martin/.virtualenvs/fysiografen_applications2016/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 210, in compress
    "No 'compress' template tags found in templates."
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.Try running compress command with --follow-links and/or--extension=EXTENSIONS

I have removed all `{% load compress %}` and `{% compress css %}{% endcompress %}` from the templates for various reasons (will user django-compressor later, though) and this crashes manage.py compress (saw this issue comment that made me realize my error: https://github.com/django-compressor/django-compressor/issues/414#issuecomment-19201471) . 

It's not a big deal since I can just remove the offline compression from my deployment script or add an empty compress tag, but isn't it more logical to return like "Nothing to compress" instead of an exception?

**Comment by intellisense** [comment]
It will also crash if you have specified `COMPRESS_OFFLINE_CONTEXT` and that returns an empty dict. I was getting this error:

```
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.Try running compress command with --follow-links and/or--extension=EXTENSIONS
```

Then I commented the `COMPRESS_OFFLINE_CONTEXT` in `settings.py` as it was returning an empty dict, everything went well afterwards.

**Comment by shiplu** [comment]
I did git bisect between 2.4.1 and 3.0. I tested it against our project. `COMPRESS_OFFLINE_CONTEXT` if not empty for us. 

From rev 2.4.1 to 877d1d118e0ca6089bc75121d2b6b8a82d17a48a, the error is not thrown. 
As soon as we hit commit 24f6648723b0b7d3ae88e17a20961ccb3ac1b1e7, the error appears. 

This might be related to #979

**Comment by shiplu** [comment]
What https://github.com/django-compressor/django-compressor/pull/995 is doing is basically removing the prefixes and keep only the a relative template path. As compressor looks in multiple directories, when a template is read, the reader checks one of those directories and can not construct the actual path. Then you have message like this (with `-v2`)

    Unreadable template at: unsupported/index.html
