### ISSUE TITLE
UnicodeDecodeError doesn't tell us which file contains the unicode

### ISSUE THREAD

**Issue by mklauber** [django-compressor/django-compressor#862]
```
Compressing... Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 291, in handle
    self.compress(sys.stdout, **options)
  File "/usr/local/lib/python2.7/dist-packages/compressor/management/commands/compress.py", line 247, in compress
    "%s" % (template.template_name, e))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 14: ordinal not in range(128)

```

Looking at the stack trace or the error message, it's not clear which file is causing the issue, or which line in the file.  A better error message would be a quality of life improvement.

**Comment by karyon** [comment]
can you try the development branch? this was most likely fixed here: https://github.com/django-compressor/django-compressor/pull/804

**Comment by mklauber** [comment]
The unicode issue goes away, but now it's saying `CommandError: An error occurred during renderingtemplates/redirect/debug.html: /usr/bin/env: ‘node’: No such file or directory` despite the fact that's not a node file. I'm going to close on the basis that my quality of life change is fixed.
