### ISSUE TITLE
pkg_resources has no attribute safe_name

### ISSUE THREAD

**Issue by jepotter1-archive** [django-compressor/django-compressor#904]
When running `pipenv install django_compressor`, the following error ocurred:
<pre><code>
Looking in indexes: https://pypi.python.org/simple
Collecting django_compressor
  Using cached https://files.pythonhosted.org/packages/02/7b/deb4605f95bcefb9760ff130533553230a1c25f4d383ed0735b075d71b29/django_compressor-2.2-py2.py3-none-any.whl
Collecting rjsmin==1.0.12 (from django_compressor)
  Using cached https://files.pythonhosted.org/packages/10/9c/2c45f57d43258b05bf33cf8f6c8161ea5abf8b4776a5c59d12646727cd98/rjsmin-1.0.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8a8ct2bd/rjsmin/setup.py", line 42, in <module>
        setup()
      File "/tmp/pip-install-8a8ct2bd/rjsmin/setup.py", line 33, in setup
        return run(script_args=args, ext=ext, manifest_only=_manifest)
      File "/tmp/pip-install-8a8ct2bd/rjsmin/_setup/py3/setup.py", line 426, in run
        return _core.setup(**kwargs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/jeremy/.local/share/virtualenvs/django-project-1vOU-KL3/lib/python3.6/site-packages/setuptools/dist.py", line 366, in __init__
        self.patch_missing_pkg_info(attrs)
      File "/home/jeremy/.local/share/virtualenvs/django-project-1vOU-KL3/lib/python3.6/site-packages/setuptools/dist.py", line 349, in patch_missing_pkg_info
        key = pkg_resources.safe_name(str(attrs['name'])).lower()
    AttributeError: module 'pkg_resources' has no attribute 'safe_name'
</code></pre>
I am using Python 3.6.3, Pip 10.0.1 and setuptools 36.2.7 inside of a virtualenv.

**Comment by jepotter1-archive** [comment]
I tried updating setuptools, it did not work. I'll file an issue on rjsmin. Thank you!
